language: node_js
node_js:
  - 12

services:
  - docker

env:
  global:
    - IMAGE_NAME=${DOCKER_ACCOUNT}/photo-market-api

install:
  - npm ci --only=production

cache: npm

script:
  - >
    echo "Build number: ${TRAVIS_BUILD_NUMBER}, Git commit hash: $(git log --format=%h -1)" > ./version.txt
  - docker build -f Dockerfile -t ${IMAGE_NAME} .

deploy:
  # deploy master to production
  - provider: script
    script: bash deploy.sh production >/dev/null 2>&1
    on:
      branch: master

  # deploy develop to the staging environment
  - provider: script
    script: bash deploy.sh staging >/dev/null 2>&1
    on:
      branch: develop



# Job lifecycle:              https://docs.travis-ci.com/user/job-lifecycle/
# Minimal and Generic images  https://docs.travis-ci.com/user/languages/minimal-and-generic/
# Using Docker in Builds      https://docs.travis-ci.com/user/docker/